package ru.nsu.fit.yus.mafia;

public enum EventType {
    GAME_STARTED,
    NIGHT_STARTED,
    NIGHT_ENDED,
    DAY_STARTED,
    GAME_ENDED,
    GAME_OVER,
    MAFIA_VOTED,
    VICTIM_CHOSEN,
    SHERIFF_CHECK,
    DOCTOR_CHOOSE,
    PLAYER_KILLED,
    PLAYER_SPOKEN,
    PLAYER_VOTED,
    PLAYER_ELIMINATED,
    //TRUST_UPDATED,
    PLAYER_ROLE_REVEALED,
    PLAYER_MESSAGE_OPTIONS,
    PLAYER_CHOOSE_TARGET,
    SHOW_LIVING_PLAYERS,
    SHOW_LIVING_MAFIA,
    SHOW_LIVING_SHERIFF,
    SHOW_LIVING_DOCTOR,
    PLAYER_LAST_WORD,
    SHOW_MESSAGE,
    NEW_VOTE,
    NOBODY_PRISONED
}

