package ru.nsu.fit.yus.mafia;

public enum EventType {
    GAME_STARTED,
    NIGHT_STARTED,
    NIGHT_ENDED,
    DAY_STARTED,
    PLAYER_KILLED,
    PLAYER_SPOKEN,
    PLAYER_VOTED,
    PLAYER_ELIMINATED,
    GAME_ENDED,
    TRUST_UPDATED,
    PLAYER_ROLE_REVEALED,
    PLAYER_MESSAGE_OPTIONS,
    PLAYER_CHOOSE_TARGET,
    LIVING_PLAYERS_UPDATED,
    PLAYER_LAST_WORD,
    SHOW_MESSAGE,
}

